apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: observability
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*

    [OUTPUT]
        Name            opensearch
        Match           *
        Host            opensearch
        Port            9200
        Index           kubernetes-logs
        Logstash_Format On
        Logstash_Prefix kubernetes
        Suppress_Type_Name On
        Replace_Dots    On


