apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000

      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.1

        ports:
        - containerPort: 9200
        - containerPort: 9300

        env:
        # Node identity
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: cluster.name
          value: "docker-cluster"

        # SINGLE NODE MODE (THIS is what stops bootstrap check)
        - name: discovery.seed_hosts
          value: "127.0.0.1"
        - name: cluster.initial_cluster_manager_nodes
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        # Disable security
        - name: plugins.security.disabled
          value: "true"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        - name: OPENSEARCH_SECURITY_DISABLED
          value: "true"
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"

        # JVM memory
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"

        volumeMounts:
        - name: opensearch-storage
          mountPath: /usr/share/opensearch/data

      volumes:
      - name: opensearch-storage
        persistentVolumeClaim:
          claimName: opensearch-pvc
