apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.11.1
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 9200
        - containerPort: 9300

        env:
        # required for k8s
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: cluster.name
          value: "opensearch"

        # CRITICAL: tells OpenSearch this is dev mode
        - name: discovery.type
          value: "single-node"

        # disable security cleanly
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"

        # memory
        - name: OPENSEARCH_JAVA_OPTS
          value: "-Xms512m -Xmx512m"

        volumeMounts:
        - name: opensearch-storage
          mountPath: /usr/share/opensearch/data

      volumes:
      - name: opensearch-storage
        persistentVolumeClaim:
          claimName: opensearch-pvc
